services:
  login_backend:
    container_name: login_backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./app/.env:/app/.env
    ports:
      - '8001:8000'
    networks:
      - securechain
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 100s
      timeout: 100s
      retries: 10
      start_period: 300s

networks:
  securechain:
    driver: bridge
