services:
  securechain-auth:
    container_name: securechain-auth
    build:
      context: ..
      dockerfile: dev/Dockerfile
    volumes:
      - ../app:/app
    env_file:
      - ../app/.env
    ports:
      - '8001:8000'
    networks:
      - securechain

networks:
  securechain:
    name: securechain
    external: true
    driver: bridge
