class DatabaseConfig:
    MIN_POOL_SIZE = 5
    MAX_POOL_SIZE = 50
    MAX_IDLE_TIME_MS = 60000
    DEFAULT_QUERY_TIMEOUT_MS = 30000

    USERS_COLLECTION = "users"
    REVOKED_TOKENS_COLLECTION = "revoked_tokens"
